[package]
name = "project_management"
version = "0.1.0"
edition = "2021"
default-run = "project_management"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "my_bin"
path = "src/bin/bin1.rs"

[dependencies]
