[package]
name = "sub_package_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sub_package_2 = {path = "../sub_package_2"}
sub_package_3 = {path = "../sub_package_3"}